{{- with .Values.alertmanager }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:

  route:
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: slack-team

    routes:
      - matchers:
          - name: severity
            value: critical
          - name: namespace
            value: prod
        receiver: slack-team

      - matchers:
          - name: severity
            value: warning
          - name: namespace
            value: prod
        receiver: slack-team # we can configure it to different receiver and send to different alert source like pagerduty but we will use slack

  receivers:
    - name: slack-team
      slackConfigs:
        - apiURL:
            name: {{ .slack.name }}
            key: {{ .slack.key }}
          channel: {{ .slack.channel | quote }}
          sendResolved: true
          text: |
            *Alert:* {{`{{ .CommonLabels.alertname }}`}}
            *Severity:* {{`{{ .CommonLabels.severity }}`}} 

            *Summary:* {{`{{ .CommonAnnotations.summary }}`}}
            *Description:* {{`{{ .CommonAnnotations.description }}`}}

          color: '{{`{{ if eq .CommonLabels.severity "critical" }}`}}danger{{`{{ else }}`}}warning{{`{{ end }}`}}'

  inhibitRules:
    - sourceMatchers:
        - name: severity
          value: critical
      targetMatchers:
        - name: severity
          value: warning
      equal:
        - alertname
        - namespace
{{- end }}